// GENERATED by scripts/build-data-js.js from /data/*.json. Edit JSON sources, then rebuild.
window.SHELLZ_DATA = {
  "providers": {
    "schema_version": "1.0",
    "updated": "2026-07-09",
    "providers": {
      "hostinger": {
        "name": "Hostinger",
        "slug": "hostinger",
        "review_url": "hostinger-review.html",
        "coupon_url": "hostinger-coupon.html",
        "affiliate_url": "https://www.hostinger.com/?tracking_id=shellz&ref=top5-2026-06",
        "tags": [
          "budget",
          "shared",
          "wordpress",
          "beginner"
        ],
        "categories": [
          "shared",
          "wordpress"
        ]
      },
      "bluehost": {
        "name": "Bluehost",
        "slug": "bluehost",
        "review_url": "bluehost-review.html",
        "coupon_url": "bluehost-coupon.html",
        "affiliate_url": "https://www.bluehost.com/track/shellz?cmp=hp-top5&utm_source=shellz&utm_medium=affiliate&utm_campaign=top5-2026-06",
        "tags": [
          "shared",
          "wordpress",
          "beginner",
          "business"
        ],
        "categories": [
          "shared",
          "wordpress"
        ]
      },
      "hostgator": {
        "name": "HostGator",
        "slug": "hostgator",
        "review_url": "hostgator-review.html",
        "coupon_url": "hostgator-coupon.html",
        "affiliate_url": "https://partners.hostgator.com/OR6JeP",
        "tags": [
          "budget",
          "shared",
          "beginner",
          "coupon"
        ],
        "categories": [
          "shared",
          "wordpress"
        ]
      },
      "siteground": {
        "name": "SiteGround",
        "slug": "siteground",
        "review_url": "siteground-review.html",
        "coupon_url": "siteground-coupon.html",
        "affiliate_url": "https://www.siteground.com/index.htm?afcode=shellz&campaign=top5-2026-06",
        "tags": [
          "wordpress",
          "managed-wordpress",
          "business",
          "performance"
        ],
        "categories": [
          "shared",
          "wordpress",
          "managed-wordpress"
        ]
      },
      "namecheap": {
        "name": "Namecheap",
        "slug": "namecheap",
        "review_url": "namecheap-review.html",
        "coupon_url": "namecheap-coupon.html",
        "affiliate_url": "https://www.namecheap.com/hosting/shared/?affId=shellz&campaign=top5-2026-06",
        "tags": [
          "budget",
          "shared",
          "domain"
        ],
        "categories": [
          "shared",
          "domain"
        ]
      },
      "namesilo": {
        "name": "NameSilo",
        "slug": "namesilo",
        "review_url": "namesilo-review.html",
        "coupon_url": "namesilo-coupon.html",
        "affiliate_url": null,
        "tags": [
          "domain",
          "budget",
          "coupon"
        ],
        "categories": [
          "domain"
        ]
      },
      "dreamhost": {
        "name": "DreamHost",
        "slug": "dreamhost",
        "review_url": "dreamhost-review.html",
        "coupon_url": "dreamhost-coupon.html",
        "affiliate_url": "https://www.dreamhost.com/track/shellz?campaign=top5-2026-06",
        "tags": [
          "shared",
          "wordpress",
          "beginner"
        ],
        "categories": [
          "shared",
          "wordpress"
        ]
      },
      "wpx": {
        "name": "WPX Hosting",
        "slug": "wpx",
        "review_url": "wpx-hosting-review.html",
        "coupon_url": "wpx-coupon.html",
        "affiliate_url": "https://wpx.net/?affid=12483",
        "tags": [
          "managed-wordpress",
          "wordpress",
          "business",
          "performance",
          "coupon"
        ],
        "categories": [
          "managed-wordpress",
          "wordpress"
        ]
      },
      "cloudways": {
        "name": "Cloudways",
        "slug": "cloudways",
        "review_url": "cloudways-review.html",
        "coupon_url": "cloudways-coupon.html",
        "affiliate_url": null,
        "tags": [
          "managed-cloud",
          "cloud",
          "performance",
          "technical"
        ],
        "categories": [
          "cloud",
          "managed-cloud"
        ]
      },
      "scalahosting": {
        "name": "ScalaHosting",
        "slug": "scalahosting",
        "review_url": "scalahosting-review.html",
        "coupon_url": "scalahosting-deals.html",
        "affiliate_url": "https://www.scalahosting.com/#shellz",
        "tags": [
          "vps",
          "managed-cloud",
          "cloud",
          "business"
        ],
        "categories": [
          "vps",
          "managed-cloud"
        ]
      },
      "ionos": {
        "name": "IONOS",
        "slug": "ionos",
        "review_url": "ionos-review.html",
        "coupon_url": "ionos-coupon.html",
        "affiliate_url": null,
        "tags": [
          "shared",
          "business",
          "budget"
        ],
        "categories": [
          "shared"
        ]
      }
    }
  },
  "pricing": {
    "schema_version": "1.0",
    "updated": "2026-07-09",
    "source_note": "Dated Shellz public-pricing research snapshots. These are not a live price feed. Missing values remain null and must not be guessed.",
    "plans": {
      "hostinger-premium": {
        "provider_key": "hostinger",
        "provider": "Hostinger",
        "plan": "Premium",
        "regionCurrency": "Provider currency; region not captured in source row",
        "introLabel": "$2.99/mo on long-term promo",
        "introMonthly": 2.99,
        "introTerm": "Long-term promo; exact term not captured in source row",
        "introTermMonths": null,
        "renewalLabel": "$10.99/mo renewal shown on provider pricing page",
        "renewalMonthly": 10.99,
        "renewalAnnual": null,
        "renewalTerm": "Provider pricing page; exact renewal cycle should be rechecked",
        "renewalTermMonths": null,
        "lastChecked": "June 2026",
        "status": "Public pricing research; verify checkout",
        "evidenceStatus": "public-pricing-research",
        "threeYearCost": null,
        "providerSource": "https://www.hostinger.com/pricing",
        "reviewUrl": "hostinger-review.html"
      },
      "bluehost-starter": {
        "provider_key": "bluehost",
        "provider": "Bluehost",
        "plan": "Starter",
        "regionCurrency": "Provider currency; region not captured in source row",
        "introLabel": "$3.99/mo commonly shown for 36-month term",
        "introMonthly": 3.99,
        "introTerm": "36 months",
        "introTermMonths": 36,
        "renewalLabel": "$9.99/mo 36-month renewal listed for Starter",
        "renewalMonthly": 9.99,
        "renewalAnnual": null,
        "renewalTerm": "36 months",
        "renewalTermMonths": 36,
        "lastChecked": "June 2026",
        "status": "Public pricing research; verify checkout",
        "evidenceStatus": "public-pricing-research",
        "threeYearCost": null,
        "providerSource": "https://www.bluehost.com/help/article/shared-hosting-prices",
        "reviewUrl": "bluehost-review.html"
      },
      "namecheap-stellar": {
        "provider_key": "namecheap",
        "provider": "Namecheap",
        "plan": "Stellar",
        "regionCurrency": "Provider currency; region not captured in source row",
        "introLabel": "From about $1.98/mo on promo",
        "introMonthly": 1.98,
        "introTerm": "Promo term varies; verify live plan",
        "introTermMonths": null,
        "renewalLabel": "$55.88/year renewal listed for Stellar after May 2026",
        "renewalMonthly": null,
        "renewalAnnual": 55.88,
        "renewalTerm": "1 year",
        "renewalTermMonths": 12,
        "lastChecked": "June 2026",
        "status": "Public pricing research; verify current pricing notice and checkout",
        "evidenceStatus": "public-pricing-research",
        "threeYearCost": null,
        "providerSource": "https://www.namecheap.com/support/knowledgebase/article.aspx/10780/22/shared-hosting-pricing-changes-may-2026/",
        "reviewUrl": "namecheap-review.html"
      },
      "siteground-startup": {
        "provider_key": "siteground",
        "provider": "SiteGround",
        "plan": "StartUp",
        "regionCurrency": "Provider currency; region not captured in source row",
        "introLabel": "Promos can be much lower than standard price",
        "introMonthly": null,
        "introTerm": "Promo term varies; verify live plan",
        "introTermMonths": null,
        "renewalLabel": "$17.99/mo for 12-month StartUp standard pricing",
        "renewalMonthly": 17.99,
        "renewalAnnual": null,
        "renewalTerm": "12 months",
        "renewalTermMonths": 12,
        "lastChecked": "June 2026",
        "status": "Public pricing research; verify checkout",
        "evidenceStatus": "public-pricing-research",
        "threeYearCost": null,
        "providerSource": "https://www.siteground.com/kb/current-rates-shared-hosting-plans/",
        "reviewUrl": "siteground-review.html"
      },
      "dreamhost-launch": {
        "provider_key": "dreamhost",
        "provider": "DreamHost",
        "plan": "Web Hosting Launch",
        "regionCurrency": "Provider currency; region not captured in source row",
        "introLabel": "First-year promo shown around $2.89/mo in provider currency",
        "introMonthly": 2.89,
        "introTerm": "First year",
        "introTermMonths": 12,
        "renewalLabel": "Auto-renews around $10.99/mo after first year in provider currency",
        "renewalMonthly": 10.99,
        "renewalAnnual": null,
        "renewalTerm": "After first year; verify current billing cycle",
        "renewalTermMonths": null,
        "lastChecked": "June 2026",
        "status": "Public pricing research; verify region, currency and checkout",
        "evidenceStatus": "public-pricing-research",
        "threeYearCost": null,
        "providerSource": "https://www.dreamhost.com/pricing/",
        "reviewUrl": "dreamhost-review.html"
      },
      "hostgator-hatchling": {
        "provider_key": "hostgator",
        "provider": "HostGator",
        "plan": "Hatchling / shared",
        "regionCurrency": "Provider currency; region not captured in source row",
        "introLabel": "Intro price changes by coupon and term",
        "introMonthly": null,
        "introTerm": "Varies",
        "introTermMonths": null,
        "renewalLabel": "Public renewal details may require account/checkout confirmation",
        "renewalMonthly": null,
        "renewalAnnual": null,
        "renewalTerm": "Not captured",
        "renewalTermMonths": null,
        "lastChecked": "June 2026",
        "status": "Coupon page published; renewal needs live confirmation",
        "evidenceStatus": "coupon-page-published",
        "threeYearCost": null,
        "providerSource": "https://www.hostgator.com/help/article/addon-price-chart",
        "reviewUrl": "hostgator-review.html"
      },
      "wpx-managed-wordpress": {
        "provider_key": "wpx",
        "provider": "WPX Hosting",
        "plan": "Managed WordPress hosting",
        "regionCurrency": "Provider currency; region not captured in source row",
        "introLabel": "Higher starting price than shared hosting",
        "introMonthly": null,
        "introTerm": "Monthly or annual; verify live plan",
        "introTermMonths": null,
        "renewalLabel": "Not a typical cheap shared-host renewal model",
        "renewalMonthly": null,
        "renewalAnnual": null,
        "renewalTerm": "Verify monthly vs annual pricing",
        "renewalTermMonths": null,
        "lastChecked": "June 2026",
        "status": "SAVE79 page published; verify checkout and eligibility",
        "evidenceStatus": "coupon-page-published",
        "threeYearCost": null,
        "providerSource": "https://wpx.net/",
        "reviewUrl": "wpx-hosting-review.html"
      },
      "cloudways-managed-cloud": {
        "provider_key": "cloudways",
        "provider": "Cloudways",
        "plan": "Managed cloud hosting",
        "regionCurrency": "Provider currency; region not captured in source row",
        "introLabel": "Monthly cloud plan pricing",
        "introMonthly": null,
        "introTerm": "Monthly / usage model",
        "introTermMonths": null,
        "renewalLabel": "Usually usage/monthly pricing, not a simple shared-host renewal",
        "renewalMonthly": null,
        "renewalAnnual": null,
        "renewalTerm": "Usage/monthly model",
        "renewalTermMonths": null,
        "lastChecked": "June 2026",
        "status": "Public plan research; compare provider, server size and add-ons",
        "evidenceStatus": "public-pricing-research",
        "threeYearCost": null,
        "providerSource": "https://www.cloudways.com/en/pricing.php",
        "reviewUrl": "cloudways-review.html"
      }
    }
  },
  "coupons": {
    "schema_version": "1.0",
    "updated": "2026-07-09",
    "status_note": "A published coupon page is not a captured checkout test. code_applied, checkout_capture and renewal_visible remain null/false until direct evidence exists.",
    "checks": {
      "hostinger-general-deal": {
        "provider_key": "hostinger",
        "code": null,
        "label": "Hostinger deal/coupon status page",
        "date_checked": null,
        "page_url": "hostinger-coupon.html",
        "page_published": true,
        "checkout_capture": false,
        "code_applied": null,
        "renewal_visible": null,
        "status": "Research page published; final cart evidence not published"
      },
      "bluehost-general-deal": {
        "provider_key": "bluehost",
        "code": null,
        "label": "Bluehost deal/coupon status page",
        "date_checked": null,
        "page_url": "bluehost-coupon.html",
        "page_published": true,
        "checkout_capture": false,
        "code_applied": null,
        "renewal_visible": null,
        "status": "Research page published; final cart evidence not published"
      },
      "hostgator-snappy": {
        "provider_key": "hostgator",
        "code": "SNAPPY",
        "label": "HostGator SNAPPY eligibility check",
        "date_checked": null,
        "page_url": "hostgator-coupon.html",
        "page_published": true,
        "checkout_capture": false,
        "code_applied": null,
        "renewal_visible": null,
        "status": "Coupon-status page published; live code result and final cart capture still required"
      },
      "wpx-save79": {
        "provider_key": "wpx",
        "code": "SAVE79",
        "label": "WPX SAVE79 eligibility check",
        "date_checked": null,
        "page_url": "wpx-coupon.html",
        "page_published": true,
        "checkout_capture": false,
        "code_applied": null,
        "renewal_visible": null,
        "status": "Eligibility page published; final checkout capture not published"
      },
      "namesilo-discount10": {
        "provider_key": "namesilo",
        "code": "DISCOUNT10",
        "label": "NameSilo DISCOUNT10 checkout note",
        "date_checked": null,
        "page_url": "namesilo-coupon.html",
        "page_published": true,
        "checkout_capture": false,
        "code_applied": null,
        "renewal_visible": null,
        "status": "Code note published; checkout outcome not captured in this ZIP"
      },
      "namesilo-namesilo10": {
        "provider_key": "namesilo",
        "code": "NAMESILO10",
        "label": "NameSilo NAMESILO10 checkout note",
        "date_checked": null,
        "page_url": "namesilo-coupon.html",
        "page_published": true,
        "checkout_capture": false,
        "code_applied": null,
        "renewal_visible": null,
        "status": "Code note published; checkout outcome not captured in this ZIP"
      },
      "namesilo-a10": {
        "provider_key": "namesilo",
        "code": "A10",
        "label": "NameSilo A10 checkout note",
        "date_checked": null,
        "page_url": "namesilo-coupon.html",
        "page_published": true,
        "checkout_capture": false,
        "code_applied": null,
        "renewal_visible": null,
        "status": "Code note published; checkout outcome not captured in this ZIP"
      }
    }
  },
  "evidence": {
    "schema_version": "1.0",
    "updated": "2026-07-09",
    "evidence_rule": "Published means the supporting result is available on Shellz. Public provider research is labelled separately from Shellz checkout, speed, uptime or support testing.",
    "providers": {
      "hostinger": {
        "public_status": true,
        "public_order": 1,
        "publicSummary": "Public plan and renewal research reviewed; dedicated deal page published.",
        "checkoutLabel": "Checkout screenshot: not published.",
        "checkout": {
          "published": false,
          "date": null,
          "url": null
        },
        "coupon": {
          "page_published": true,
          "tested": false
        },
        "renewal": {
          "status": "public-pricing-example",
          "plan_keys": [
            "hostinger-premium"
          ]
        },
        "speed": {
          "published": false
        },
        "uptime": {
          "published": false
        },
        "support": {
          "published": false
        },
        "next_action": "Match exact plan, capture promo term and final cart total"
      },
      "bluehost": {
        "public_status": true,
        "public_order": 2,
        "publicSummary": "Starter plan renewal example is documented in the Shellz tracker.",
        "checkoutLabel": "Checkout screenshot: not published.",
        "checkout": {
          "published": false,
          "date": null,
          "url": null
        },
        "coupon": {
          "page_published": true,
          "tested": false
        },
        "renewal": {
          "status": "public-pricing-example",
          "plan_keys": [
            "bluehost-starter"
          ]
        },
        "speed": {
          "published": false
        },
        "uptime": {
          "published": false
        },
        "support": {
          "published": false
        },
        "next_action": "Verify Starter plan, currency and 36-month cart total"
      },
      "hostgator": {
        "public_status": true,
        "public_order": 3,
        "publicSummary": "SNAPPY is covered on a dedicated coupon-status page with eligibility warnings.",
        "checkoutLabel": "Final checkout capture: not published.",
        "checkout": {
          "published": false,
          "date": null,
          "url": null
        },
        "coupon": {
          "page_published": true,
          "tested": false,
          "check_keys": [
            "hostgator-snappy"
          ]
        },
        "renewal": {
          "status": "live-confirmation-required",
          "plan_keys": [
            "hostgator-hatchling"
          ]
        },
        "speed": {
          "published": false
        },
        "uptime": {
          "published": false
        },
        "support": {
          "published": false
        },
        "next_action": "Test SNAPPY, save exact plan, term, final total and renewal line"
      },
      "wpx": {
        "public_status": true,
        "public_order": 4,
        "publicSummary": "SAVE79 is covered as a first-month eligibility check for monthly WordPress hosting.",
        "checkoutLabel": "Final checkout capture: not published.",
        "checkout": {
          "published": false,
          "date": null,
          "url": null
        },
        "coupon": {
          "page_published": true,
          "tested": false,
          "check_keys": [
            "wpx-save79"
          ]
        },
        "renewal": {
          "status": "live-term-check-required",
          "plan_keys": [
            "wpx-managed-wordpress"
          ]
        },
        "speed": {
          "published": false
        },
        "uptime": {
          "published": false
        },
        "support": {
          "published": false
        },
        "next_action": "Verify eligible monthly plan, first-month result and normal next charge"
      },
      "siteground": {
        "public_status": false,
        "checkout": {
          "published": false
        },
        "coupon": {
          "page_published": true,
          "tested": false
        },
        "renewal": {
          "status": "public-pricing-example",
          "plan_keys": [
            "siteground-startup"
          ]
        },
        "speed": {
          "published": false
        },
        "uptime": {
          "published": false
        },
        "support": {
          "published": false
        },
        "next_action": "Capture exact StartUp promo term and checkout"
      },
      "namecheap": {
        "public_status": false,
        "checkout": {
          "published": false
        },
        "coupon": {
          "page_published": true,
          "tested": false
        },
        "renewal": {
          "status": "public-pricing-example",
          "plan_keys": [
            "namecheap-stellar"
          ]
        },
        "speed": {
          "published": false
        },
        "uptime": {
          "published": false
        },
        "support": {
          "published": false
        },
        "next_action": "Capture exact Stellar promo term and checkout"
      },
      "namesilo": {
        "public_status": false,
        "checkout": {
          "published": false
        },
        "coupon": {
          "page_published": true,
          "tested": false,
          "check_keys": [
            "namesilo-discount10",
            "namesilo-namesilo10",
            "namesilo-a10"
          ]
        },
        "renewal": {
          "status": "not-structured",
          "plan_keys": []
        },
        "speed": {
          "published": false
        },
        "uptime": {
          "published": false
        },
        "support": {
          "published": false
        },
        "next_action": "Test one code at a time and record before/after total"
      },
      "dreamhost": {
        "public_status": false,
        "checkout": {
          "published": false
        },
        "coupon": {
          "page_published": true,
          "tested": false
        },
        "renewal": {
          "status": "public-pricing-example",
          "plan_keys": [
            "dreamhost-launch"
          ]
        },
        "speed": {
          "published": false
        },
        "uptime": {
          "published": false
        },
        "support": {
          "published": false
        },
        "next_action": "Capture region/currency and exact renewal billing cycle"
      },
      "cloudways": {
        "public_status": false,
        "checkout": {
          "published": false
        },
        "coupon": {
          "page_published": true,
          "tested": false
        },
        "renewal": {
          "status": "usage-model",
          "plan_keys": [
            "cloudways-managed-cloud"
          ]
        },
        "speed": {
          "published": false
        },
        "uptime": {
          "published": false
        },
        "support": {
          "published": false
        },
        "next_action": "Structure server size, provider, add-ons and monthly usage model"
      },
      "scalahosting": {
        "public_status": false,
        "checkout": {
          "published": false
        },
        "coupon": {
          "page_published": true,
          "tested": false
        },
        "renewal": {
          "status": "not-structured",
          "plan_keys": []
        },
        "speed": {
          "published": false
        },
        "uptime": {
          "published": false
        },
        "support": {
          "published": false
        },
        "next_action": "Capture exact managed cloud/VPS plan and term separately"
      },
      "ionos": {
        "public_status": false,
        "checkout": {
          "published": false
        },
        "coupon": {
          "page_published": true,
          "tested": false
        },
        "renewal": {
          "status": "not-structured",
          "plan_keys": []
        },
        "speed": {
          "published": false
        },
        "uptime": {
          "published": false
        },
        "support": {
          "published": false
        },
        "next_action": "Add an exact plan pricing row before renewal comparisons"
      }
    }
  }
};
window.SHELLZ_HOSTING_PRICE_SNAPSHOTS = window.SHELLZ_DATA.pricing.plans;
(function(){
  function text(value){ return value === null || value === undefined ? '' : String(value); }
  function hydrate(){
    var plans = (window.SHELLZ_DATA && window.SHELLZ_DATA.pricing && window.SHELLZ_DATA.pricing.plans) || {};
    var evidence = (window.SHELLZ_DATA && window.SHELLZ_DATA.evidence && window.SHELLZ_DATA.evidence.providers) || {};
    document.querySelectorAll('[data-price-key][data-price-field]').forEach(function(node){
      var row = plans[node.getAttribute('data-price-key')];
      var field = node.getAttribute('data-price-field');
      if (row && row[field] !== undefined && row[field] !== null) node.textContent = text(row[field]);
    });
    document.querySelectorAll('[data-evidence-provider][data-evidence-field]').forEach(function(node){
      var row = evidence[node.getAttribute('data-evidence-provider')];
      var field = node.getAttribute('data-evidence-field');
      if (row && row[field] !== undefined && row[field] !== null) node.textContent = text(row[field]);
    });
    document.dispatchEvent(new CustomEvent('shellz:data-ready', {detail: window.SHELLZ_DATA}));
  }
  if(document.readyState === 'loading') document.addEventListener('DOMContentLoaded', hydrate); else hydrate();
})();
