const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const read = (name) => JSON.parse(fs.readFileSync(path.join(root, 'data', name), 'utf8'));
const data = {
  providers: read('providers.json'),
  pricing: read('pricing.json'),
  coupons: read('coupon-checks.json'),
  evidence: read('evidence.json')
};
const payload = JSON.stringify(data, null, 2);
const output = `// GENERATED by scripts/build-data-js.js from /data/*.json. Edit JSON sources, then rebuild.\n` +
`window.SHELLZ_DATA = ${payload};\n` +
`window.SHELLZ_HOSTING_PRICE_SNAPSHOTS = window.SHELLZ_DATA.pricing.plans;\n` +
`(function(){\n` +
`  function text(value){ return value === null || value === undefined ? '' : String(value); }\n` +
`  function hydrate(){\n` +
`    var plans = (window.SHELLZ_DATA && window.SHELLZ_DATA.pricing && window.SHELLZ_DATA.pricing.plans) || {};\n` +
`    var evidence = (window.SHELLZ_DATA && window.SHELLZ_DATA.evidence && window.SHELLZ_DATA.evidence.providers) || {};\n` +
`    document.querySelectorAll('[data-price-key][data-price-field]').forEach(function(node){\n` +
`      var row = plans[node.getAttribute('data-price-key')];\n` +
`      var field = node.getAttribute('data-price-field');\n` +
`      if (row && row[field] !== undefined && row[field] !== null) node.textContent = text(row[field]);\n` +
`    });\n` +
`    document.querySelectorAll('[data-evidence-provider][data-evidence-field]').forEach(function(node){\n` +
`      var row = evidence[node.getAttribute('data-evidence-provider')];\n` +
`      var field = node.getAttribute('data-evidence-field');\n` +
`      if (row && row[field] !== undefined && row[field] !== null) node.textContent = text(row[field]);\n` +
`    });\n` +
`    document.dispatchEvent(new CustomEvent('shellz:data-ready', {detail: window.SHELLZ_DATA}));\n` +
`  }\n` +
`  if(document.readyState === 'loading') document.addEventListener('DOMContentLoaded', hydrate); else hydrate();\n` +
`})();\n`;
fs.writeFileSync(path.join(root, 'shellz-data.js'), output);
console.log('Built shellz-data.js from 4 JSON sources');
